imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        enabled: true
        collect: true

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        driver:   pdo_sqlite
        dbname:   %database_name%
        charset:  UTF8
        path:     %kernel.cache_dir%/test.db

liip_functional_test:
  cache_sqlite_db: true
  authentication:
    username: test
    password: test

security:
  firewalls:
    main:
      http_basic: ~