app:
  resource: "@AppBundle/Controller/"
  type:     annotation
  options:
      expose: true

fos_js_routing:
  resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

dende_calendar:
  type: annotation
  resource: @DendeCalendarBundle/Controller/DefaultController.php
  prefix: calendar
  options:
      expose: true