---
parameters:
  workshop.class:               AppBundle\Entity\Workshop
  lesson.class:                 AppBundle\Entity\Lesson
  lesson.class.command.create:  AppBundle\Command\CreateLesson
  lesson.class.command.update:  AppBundle\Command\UpdateLesson

services:
  app.form.transform.lesson_command:
    class: AppBundle\Form\Transformer\LessonToCommand
    arguments:
      - @app.factory.lesson
    calls:
      - [setCommandClass, [%lesson.class.command.create%]]

  app.form.register_workshops_form_type:
    class: AppBundle\Form\RegisterWorkshopsFormType
    tags:
        - { name: form.type, alias: register_workshops_form_type }

  app.form.search:
    class: AppBundle\Form\SearchType
    tags:
        - { name: form.type, alias: search_workshop }

  app.repository.workshop:
    class: AppBundle\Entity\WorkshopRepository
    factory: [@doctrine.orm.entity_manager, getRepository]
    arguments:
      - %workshop.class%

  app.repository.lesson:
    class: AppBundle\Entity\LessonRepository
    factory: [@doctrine.orm.entity_manager, getRepository]
    arguments:
      - %lesson.class%

  app.handler.create_workshop:
    class: AppBundle\Handler\CreateWorkshopHandler
    arguments:
      - @app.factory.workshop
      - @app.repository.workshop
      - @app.factory.lesson
    tags:
      - {name: tactician.handler, command: AppBundle\Command\CreateWorkshop }

  app.handler.update_workshop:
    class: AppBundle\Handler\UpdateWorkshopHandler
    arguments:
      - @app.repository.workshop
      - @app.generator.workshop_slug
    tags:
      - {name: tactician.handler, command: AppBundle\Command\UpdateWorkshop }

  app.generator.null:
    class: AppBundle\Generator\NullGenerator

  app.generator.workshop_slug:
    class: AppBundle\Generator\WorkshopSlugGenerator
    arguments:
      - @app.repository.workshop

  app.factory.workshop:
    class: AppBundle\Factory\WorkshopFactory
    arguments:
      - @app.generator.null
      - @app.generator.workshop_slug

  app.factory.lesson:
    class: AppBundle\Factory\LessonFactory
    arguments:
      - @app.generator.null
      - @app.repository.lesson