---
parameters:
  workshop.class:               AppBundle\Entity\Workshop
  lesson.class:                 AppBundle\Entity\Lesson
  lesson.class.command.create:  AppBundle\Command\CreateLesson
  lesson.class.command.update:  AppBundle\Command\UpdateLesson

services:
  app.helper.workshops_json_wrapper:
    class: AppBundle\Controller\Helper\WorkshopsJsonWrapper
    arguments:
      - @router

  app.helper.lesson_json_wrapper:
    class: AppBundle\Controller\Helper\LessonsJsonWrapper
    arguments:
      - @router

  app.form.transform.lesson_command:
    class: AppBundle\Form\Transformer\LessonToCommand
    arguments:
      - @app.factory.lesson
    calls:
      - [setCommandClass, [%lesson.class.command.create%]]

  app.form.register_workshops_form_type:
    class: AppBundle\Form\RegisterWorkshopsFormType
    tags:
        - { name: form.type, alias: register_workshops_form_type }

  app.form.search:
    class: AppBundle\Form\SearchType
    tags:
        - { name: form.type, alias: search_workshop }

  app.repository.workshop:
    class: AppBundle\Entity\WorkshopRepository
    factory: [@doctrine.orm.entity_manager, getRepository]
    arguments:
      - %workshop.class%

  app.repository.lesson:
    class: AppBundle\Entity\LessonRepository
    factory: [@doctrine.orm.entity_manager, getRepository]
    arguments:
      - %lesson.class%

  app.handler.create_workshop:
    class: AppBundle\Handler\CreateWorkshopHandler
    arguments:
      - @app.repository.workshop
      - @dende_calendar.calendar_repository
      - @dende_calendar.event_repository
      - @app.factory.workshop
      - @app.factory.lesson
      - @dende_calendar.factory.event
      - @dende_calendar.factory.occurrence
    tags:
      - {name: tactician.handler, command: AppBundle\Command\CreateWorkshop }

  app.handler.create_event:
    class: Dende\Calendar\Application\Handler\CreateEventHandler
    parent: dende_calendar.handler.create_event
    tags:
      - {name: tactician.handler, command: Dende\Calendar\Application\Command\CreateEventCommand }

  app.handler.update_workshop:
    class: AppBundle\Handler\UpdateWorkshopHandler
    arguments:
      - @app.repository.workshop
      - @app.repository.lesson
      - @app.generator.workshop_slug
    tags:
      - {name: tactician.handler, command: AppBundle\Command\UpdateWorkshop }

#  app.handler.update_lesson_collection:
#    class: AppBundle\Handler\UpdateLessonCollectionHandler
#    arguments:
#      - @app.repository.lesson
#    tags:
#      - {name: tactician.handler, command: AppBundle\Command\UpdateWorkshop }

  app.generator.null:
    class: AppBundle\Generator\NullGenerator

  app.generator.workshop_slug:
    class: AppBundle\Generator\WorkshopSlugGenerator
    arguments:
      - @app.repository.workshop

  app.factory.workshop:
    class: AppBundle\Factory\WorkshopFactory
    arguments:
      - @app.generator.null
      - @app.generator.workshop_slug

  app.factory.lesson:
    class: AppBundle\Factory\LessonFactory
    arguments:
      - @app.generator.null
      - @app.repository.lesson
