---
AppBundle\Entity\Workshop:
  type:   entity
  table:  workshops
  repositoryClass:  AppBundle\Entity\WorkshopRepository

  id:
    id:
      type: guid
      generator: { strategy: UUID }

  oneToMany:
    lessons:
      targetEntity: AppBundle\Entity\Lesson
      mappedBy: workshop
      cascade: ["all"]

  fields:
    title:
      type: string
      nullable: false
    description:
      type: text
      nullable: false

    startDate:
      type: datetime

    endDate:
      type: datetime

    url:
      type: string

    phone:
      type: string

    email:
      type: string

    city:
      type: string

    slug:
      type: string
      unique: true